[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'no build step needed'"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/progress"
  to = "/.netlify/functions/get-progress-data"
  status = 200

[[redirects]]
  from = "/api/lead-data"
  to = "/.netlify/functions/get-lead-data"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
